# Generated by Django 3.0.4 on 2020-03-12 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=100)),
                ('nombre_tecnico', models.CharField(max_length=40)),
                ('gerente', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, default='logosequipo/default.png', null=True, upload_to='logosequipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='fotosjugadores/default.png', null=True, upload_to='fotosjugadores')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Equipo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
